name: "decode_dbt"
version: "1.0"
config-version: 2

profile: "decode_dbt_profile"

model-paths: ["models"]
seed-paths: ["models/seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  decode_dbt:
    +materialized: table