version: 2

models:
  - name: my_first_model
    description: "A simple model showing positive orders."
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: amount
        description: "Order value in USD"